name: Create release branch

on:
  workflow_dispatch:
    inputs:
      newVersionNumber:
        description: 'New version number'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1

      - name: Replace version
        run: |
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./plugins/sqlfluff-templater-dbt/setup.cfg
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg
          sed -i -e '/stable_version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg

      - name: Commit
        run: |
          git add .
          git commit -m "Bump to version ${{ github.event.inputs.newVersionNumber }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
