name: Create release branch

on:
  workflow_dispatch:
    inputs:
      newVersionNumber:
        description: 'New version number'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1

      - name: Replace version
        run: |
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./plugins/sqlfluff-templater-dbt/setup.cfg
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg
          sed -i -e '/stable_version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg

      - name: Push to feature branch
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout -b prep-${{ github.event.inputs.newVersionNumber }}
          git add .
          git commit -m "Bump to version ${{ github.event.inputs.newVersionNumber }}"
          git push --set-upstream origin prep-${{ github.event.inputs.newVersionNumber }}
