name: Create release pull request

on:
  workflow_dispatch:
    inputs:
      newVersionNumber:
        description: 'New version number'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1

      - name: Replace version
        run: |
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./plugins/sqlfluff-templater-dbt/setup.cfg
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg
          sed -i -e '/stable_version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg

      - name: Start Changelog entry
        run: |
          sed -i 's/-->/-->\n\n## [${{ github.event.inputs.newVersionNumber }}] - ${date + "%Y-%m-%d"}\n\n## Highlights\n\n## What’s Changed\n\n## New Contributors/' ./CHANGELOG.md

      - name: Commit
        run: |
          git add .
          git commit -m "Bump to version ${{ github.event.inputs.newVersionNumber }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          branch: prep-${{ github.event.inputs.newVersionNumber }}
          branch-suffix: short-commit-hash
          title: Prep version ${{ github.event.inputs.newVersionNumber }}
